# Generated by Django 2.1.15 on 2021-07-20 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='netbank_Model',
            fields=[
                ('Sr_No', models.IntegerField(primary_key='Sr_No', serialize=False)),
                ('Promo_code', models.CharField(max_length=4000)),
                ('Cust_Id', models.IntegerField()),
                ('Customer_Name', models.CharField(max_length=400)),
                ('Eligible_Programme', models.CharField(max_length=4000)),
                ('Account_no', models.IntegerField()),
                ('Home_BranchName', models.IntegerField()),
                ('Home_BranchCode', models.IntegerField()),
                ('CR_programme_RM_Change', models.CharField(max_length=4000)),
                ('Credit_Card', models.CharField(max_length=4000)),
                ('DC_Upgrade', models.CharField(max_length=4000)),
                ('Selected_Branchname', models.CharField(max_length=4000)),
                ('Selected_Branchcode', models.IntegerField()),
                ('Employee_Code', models.CharField(max_length=4000)),
                ('Confirmation_authorize', models.CharField(max_length=4000)),
                ('IP_Address', models.CharField(max_length=4000)),
                ('Session_Id', models.CharField(max_length=4000)),
                ('User_Agent', models.CharField(max_length=4000)),
                ('Lead_Date', models.CharField(max_length=4000)),
                ('Confirmation_Authorize_for_Debit_Card', models.CharField(max_length=4000)),
                ('Confirmation_Authorize_for_Credit_Card', models.CharField(max_length=4000)),
            ],
            options={
                'db_table': 'netbanking',
            },
        ),
        migrations.CreateModel(
            name='sms_eva_Model',
            fields=[
                ('pseudoId', models.IntegerField()),
                ('pcId', models.IntegerField()),
                ('mobilenumber', models.IntegerField(primary_key='mobilenumber', serialize=False)),
                ('current_category', models.CharField(max_length=4000)),
                ('eligible_category', models.CharField(max_length=4000)),
                ('consent_of_user', models.CharField(max_length=4000)),
                ('consent_time', models.CharField(max_length=4000)),
                ('CustomerName', models.CharField(max_length=4000)),
                ('existing_branch', models.CharField(max_length=4000)),
                ('change_branch', models.CharField(max_length=4000)),
                ('change_rm', models.CharField(max_length=4000)),
                ('employee_code', models.CharField(max_length=4000)),
                ('state', models.CharField(max_length=4000)),
                ('city', models.CharField(max_length=4000)),
                ('branch', models.CharField(max_length=4000)),
                ('branch_code', models.IntegerField()),
                ('existing_branch_code', models.IntegerField()),
                ('sessionID', models.CharField(max_length=4000)),
                ('IPaddress', models.CharField(max_length=4000)),
                ('channel_remarks', models.CharField(max_length=4000)),
                ('device', models.CharField(max_length=4000)),
            ],
            options={
                'db_table': 'sms_eva',
            },
        ),
    ]
