# Generated by Django 2.1.15 on 2021-08-05 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='netbanking_Model',
            fields=[
                ('Sr_No', models.IntegerField(primary_key='Sr_No', serialize=False)),
                ('Promo_code', models.CharField(max_length=4000)),
                ('Pseudo_Id', models.CharField(max_length=4000)),
                ('Customer_Name', models.CharField(max_length=400)),
                ('Eligible_Programme', models.CharField(max_length=4000)),
                ('Account_no', models.IntegerField()),
                ('Home_BranchName', models.CharField(max_length=4000)),
                ('Home_BranchCode', models.IntegerField()),
                ('CR_programme_RM_Change', models.CharField(max_length=4000)),
                ('Credit_Card', models.CharField(max_length=4000)),
                ('DC_Upgrade', models.CharField(max_length=4000)),
                ('Selected_Branchname', models.CharField(max_length=4000)),
                ('Selected_Branchcode', models.IntegerField()),
                ('Employee_Code', models.CharField(max_length=4000)),
                ('Confirmation_authorize', models.CharField(max_length=4000)),
                ('IP_Address', models.CharField(max_length=4000)),
                ('Session_Id', models.CharField(max_length=4000)),
                ('User_Agent', models.CharField(max_length=4000)),
                ('Lead_Date', models.CharField(max_length=4000)),
                ('Confirmation_Authorize_for_Debit_Card', models.CharField(max_length=4000)),
                ('Confirmation_Authorize_for_Credit_Card', models.CharField(max_length=4000)),
            ],
            options={
                'db_table': 'netbank',
            },
        ),
        migrations.DeleteModel(
            name='netbank_Model',
        ),
        migrations.AlterField(
            model_name='sms_eva_model',
            name='branch_code',
            field=models.CharField(max_length=4000),
        ),
        migrations.AlterField(
            model_name='sms_eva_model',
            name='mobilenumber',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='sms_eva_model',
            name='pcId',
            field=models.CharField(max_length=4000),
        ),
        migrations.AlterField(
            model_name='sms_eva_model',
            name='pseudoId',
            field=models.CharField(max_length=4000, primary_key='pseudoId', serialize=False),
        ),
        migrations.AlterModelTable(
            name='sms_eva_model',
            table='smseva',
        ),
    ]
